CREATE TABLE books (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    book_name TEXT NOT NULL,
    date_created TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE book_content (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    plot TEXT,
    bookId INTEGER REFERENCES books(id),
    date_created TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE characters (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    character_name TEXT NOT NULL,
    char_description TEXT,
    bookContentId INTEGER REFERENCES book_content(id),
    date_created TIMESTAMP NOT NULL DEFAULT now()
);