TRUNCATE
    book_content
    RESTART IDENTITY CASCADE;

INSERT INTO book_content (title, plot, book_id)
VALUES
    ('Book One Title', 'Irure duis amet pariatur commodo consequat culpa non tempor id veniam. Culpa exercitation culpa id nulla. Ex dolor Lorem officia commodo irure culpa. Sint commodo minim voluptate nulla adipisicing labore ea pariatur sunt veniam anim. Labore consequat commodo fugiat sit deserunt voluptate nisi aliquip duis qui. Enim tempor ullamco reprehenderit duis incididunt minim consequat incididunt est dolor est.', 1),
    ('Book Two Title', 'Irure duis amet pariatur commodo consequat culpa non tempor id veniam. Culpa exercitation culpa id nulla. Ex dolor Lorem officia commodo irure culpa. Sint commodo minim voluptate nulla adipisicing labore ea pariatur sunt veniam anim. Labore consequat commodo fugiat sit deserunt voluptate nisi aliquip duis qui. Enim tempor ullamco reprehenderit duis incididunt minim consequat incididunt est dolor est.', 2),
    ('Book Three Title', 'Irure duis amet pariatur commodo consequat culpa non tempor id veniam. Culpa exercitation culpa id nulla. Ex dolor Lorem officia commodo irure culpa. Sint commodo minim voluptate nulla adipisicing labore ea pariatur sunt veniam anim. Labore consequat commodo fugiat sit deserunt voluptate nisi aliquip duis qui. Enim tempor ullamco reprehenderit duis incididunt minim consequat incididunt est dolor est.', 3),
    ('Book Four Title', 'Irure duis amet pariatur commodo consequat culpa non tempor id veniam. Culpa exercitation culpa id nulla. Ex dolor Lorem officia commodo irure culpa. Sint commodo minim voluptate nulla adipisicing labore ea pariatur sunt veniam anim. Labore consequat commodo fugiat sit deserunt voluptate nisi aliquip duis qui. Enim tempor ullamco reprehenderit duis incididunt minim consequat incididunt est dolor est.', 1),
    ('Book Five Title', 'Irure duis amet pariatur commodo consequat culpa non tempor id veniam. Culpa exercitation culpa id nulla. Ex dolor Lorem officia commodo irure culpa. Sint commodo minim voluptate nulla adipisicing labore ea pariatur sunt veniam anim. Labore consequat commodo fugiat sit deserunt voluptate nisi aliquip duis qui. Enim tempor ullamco reprehenderit duis incididunt minim consequat incididunt est dolor est.', 3);